import 'package:flutter_test/flutter_test.dart';
import 'package:finite_field_calculator/parsing.dart';

void main() {
  group('Implicit Multiplication and Parsing', () {
    test('Injects multiplication after inverse symbol', () {
      // 2⁻¹5 should be parsed as 2⁻¹ * 5
      // In Z_7, 2⁻¹ is 4. 4 * 5 = 20. 20 mod 7 = 6.
      final result = evaluateExpression("2⁻¹5", 7, false, "");
      expect(result, equals("6"));
    });

    test('Handles implicit multiplication with variables', () {
      // x⁻¹x should result in 1 (identity)
      final result = evaluateExpression("x⁻¹x", 7, true, "x^2+1");
      expect(result, equals("1"));
    });

    test('Processes negative exponent decomposition', () {
      // This tests if the underlying parser handles the string
      // generated by the UI: x⁻¹^2
      final result = evaluateExpression("x⁻¹^2", 11, true, "x^3+x+1");
      // x⁻¹^2 is (x⁻¹)²
      // This relies on your inverseMod and polyPow implementations
      expect(result, isNot(contains("Error")));
    });
  });

  group('Finite Field Arithmetic', () {
    test('Scalar inversion in Z_p', () {
      // 3 * x = 1 mod 5 -> x = 2
      final result = evaluateExpression("3⁻¹", 5, false, "");
      expect(result, equals("2"));
    });

    test('Polynomial Modulo Reduction', () {
      // (x^2 + 1) mod (x^2) should be 1
      final result = evaluateExpression("x^2+1", 7, true, "x^2");
      expect(result, equals("1"));
    });

    test('Complex expression with precedence', () {
      // 2 + 3 × 4 in Z_11: 2 + 12 = 14 -> 3
      final result = evaluateExpression("2+3×4", 11, false, "");
      expect(result, equals("3"));
    });
  });

  group('Error Handling', () {
    test('Throws error on division by zero', () {
      expect(
        () => evaluateExpression("0⁻¹", 7, false, ""),
        throwsArgumentError,
      );
    });

    test('Throws error for missing modulus in poly mode inversion', () {
      // isPoly = true, but empty modStr
      expect(() => evaluateExpression("x⁻¹", 7, true, ""), throwsArgumentError);
    });
  });
}
